### ISSUE TITLE
Crash on start of the app `com.appsflyer.internal.AFa1xSDK$$.AFInAppEventType`

### ISSUE THREAD

**Issue by scana** [AppsFlyerSDK/appsflyer-segment-android-plugin#88]
# Report

Hi! 
Right after updating to the most recent version we've observed increased amount of crashes that point to AppsFlyer integration.
Please let me know if I can be of any more help regarding this issue.

## Plugin Version

`6.10.3`

## Please provide any other relevant information.

Crash encountered on production:
```
Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1xSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1xSDK$$>
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:425)
       at com.appsflyer.internal.AFa1xSDK$$.AFInAppEventType(:100)
       at com.appsflyer.internal.AFa1xSDK$$.AFInAppEventParameterName(:26)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:425)
       at com.appsflyer.internal.AFa1vSDK.AFInAppEventParameterName(:3)
       at com.appsflyer.internal.AFc1kSDK.AFInAppEventType(:140)
       at com.appsflyer.internal.AFd1cSDK.AFInAppEventParameterName(:87)
       at com.appsflyer.internal.AFd1iSDK.valueOf(:114)
       at com.appsflyer.internal.AFd1pSDK$5.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

- It is marked as an early crash - which means that it crashed in user's first 5 seconds.
- So far it has happened on Xiaomi and Samsung devices running Android 11 only.

**Comment by morisgateno-appsflyer** [comment]
👋 Hi @scana  and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
